// Generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY - This file is auto-generated during build

export const VERSION = "0.1.0"
export const COMMIT_HASH = "b570332"
export const DISPLAY_VERSION = "v0.1.0 (b570332) (dev)"
export const IS_COMPILED = false
