#!/usr/bin/env bun
/**
 * Generate version.ts module with build-time version info
 * Captures: package.json version, git commit hash, dev vs compiled mode
 */

import { $ } from "bun"
import { resolve, join } from "path"
import { existsSync } from "fs"

const PROJECT_ROOT = resolve(import.meta.dir, "..")
const OUTPUT_FILE = join(PROJECT_ROOT, "src", "server", "version.ts")

async function main() {
  // Read version from package.json
  const packageJson = await Bun.file(join(PROJECT_ROOT, "package.json")).json()
  const version = packageJson.version || "0.0.0"

  // Get short git commit hash
  let commitHash: string
  try {
    const result = await $`git -C ${PROJECT_ROOT} rev-parse --short HEAD`.text()
    commitHash = result.trim()
  } catch {
    commitHash = "unknown"
  }

  // Check if running as compiled binary
  // In compiled binaries, import.meta.url is different and package.json won't exist in expected location
  const isCompiled = !existsSync(join(PROJECT_ROOT, "package.json")) ||
                     import.meta.url.includes("/tmp/") || // Bun compile temp path
                     import.meta.url.includes("/.bun/") // Bun runtime path

  const devSuffix = isCompiled ? "" : " (dev)"

  // Generate version string: v1.0.0 (a2e8dcd) or v1.0.0 (a2e8dcd) (dev)
  const displayVersion = `v${version} (${commitHash})${devSuffix}`

  const moduleContent = `// Generated by scripts/generate-version.ts
// DO NOT EDIT MANUALLY - This file is auto-generated during build

export const VERSION = "${version}"
export const COMMIT_HASH = "${commitHash}"
export const DISPLAY_VERSION = "${displayVersion}"
export const IS_COMPILED = ${isCompiled}
`

  await Bun.write(OUTPUT_FILE, moduleContent)
  console.log(`✓ Generated version.ts: ${displayVersion}`)
}

if (import.meta.main) {
  void main().catch((err) => {
    console.error("❌ Failed to generate version:", err)
    process.exit(1)
  })
}

export { main as generateVersion }
