#!/usr/bin/env bun
/**
 * Generate embedded assets module for compiled binary
 * 
 * This script reads all files from kanban-vue/dist and generates a TypeScript
 * module that exports them as data URIs or strings that can be served directly.
 */

import { $ } from "bun"
import { existsSync, readdirSync, statSync, readFileSync } from "fs"
import { resolve, join, relative } from "path"

const PROJECT_ROOT = resolve(import.meta.dir, "..")
const KANBAN_VUE_DIR = join(PROJECT_ROOT, "src", "kanban-vue")
const DIST_DIR = join(KANBAN_VUE_DIR, "dist")
const ASSETS_DIR = join(DIST_DIR, "assets")
const OUTPUT_FILE = join(PROJECT_ROOT, "src", "server", "generated-assets.ts")

interface AssetFile {
  path: string
  relativePath: string
  contentType: string
  isText: boolean
  data: string
}

function getContentType(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase()
  const types: Record<string, string> = {
    html: "text/html",
    js: "application/javascript",
    css: "text/css",
    svg: "image/svg+xml",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    woff2: "font/woff2",
    woff: "font/woff",
    ttf: "font/ttf",
    json: "application/json",
    ico: "image/x-icon",
  }
  return types[ext || ""] || "application/octet-stream"
}

function shouldInlineAsText(contentType: string): boolean {
  return contentType.startsWith("text/") || 
         contentType === "application/javascript" ||
         contentType === "application/json"
}

function collectFiles(dir: string, basePath: string = ""): AssetFile[] {
  const files: AssetFile[] = []
  
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry)
    const relativePath = basePath ? `${basePath}/${entry}` : entry
    const stat = statSync(fullPath)
    
    if (stat.isDirectory()) {
      files.push(...collectFiles(fullPath, relativePath))
    } else {
      const contentType = getContentType(entry)
      const isText = shouldInlineAsText(contentType)
      
      if (isText) {
        // Read as text for text files
        const content = readFileSync(fullPath, "utf-8")
        files.push({
          path: fullPath,
          relativePath,
          contentType,
          isText: true,
          data: content,
        })
      } else {
        // Read as base64 for binary files
        const buffer = readFileSync(fullPath)
        const base64 = buffer.toString("base64")
        files.push({
          path: fullPath,
          relativePath,
          contentType,
          isText: false,
          data: base64,
        })
      }
    }
  }
  
  return files
}

function generateAssetsModule(files: AssetFile[]): string {
  const lines: string[] = []
  
  lines.push("// Generated by scripts/generate-embedded-assets.ts")
  lines.push("// DO NOT EDIT MANUALLY - This file is auto-generated during build")
  lines.push("")
  lines.push("export interface EmbeddedAsset {")
  lines.push("  contentType: string")
  lines.push("  isText: boolean")
  lines.push("  data: string")
  lines.push("}")
  lines.push("")
  lines.push("export const embeddedAssets: Map<string, EmbeddedAsset> = new Map([")
  
  for (const file of files) {
    const key = file.relativePath.startsWith("assets/") 
      ? `/${file.relativePath}`
      : `/${file.relativePath}`
    
    if (file.isText) {
      // For text files, escape backticks and ${ to prevent template literal issues
      const escaped = file.data
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$/g, "\\$")
        .replace(/\n/g, "\\n")
        .replace(/\r/g, "\\r")
      
      lines.push(`  ["${key}", { contentType: "${file.contentType}", isText: true, data: \`${escaped}\` }],`)
    } else {
      // For binary files, store base64
      lines.push(`  ["${key}", { contentType: "${file.contentType}", isText: false, data: "${file.data}" }],`)
    }
  }
  
  lines.push("])")
  lines.push("")
  lines.push("// Convenience accessors")
  lines.push("export function getEmbeddedAsset(path: string): EmbeddedAsset | undefined {")
  lines.push("  // Normalize path - remove leading /kanban-vue/dist if present")
  lines.push('  const normalized = path.replace(/^\\/kanban-vue\\/dist/, "")')
  lines.push("  return embeddedAssets.get(normalized)")
  lines.push("}")
  lines.push("")
  lines.push("export function getIndexHtml(): string | undefined {")
  lines.push('  return embeddedAssets.get("/index.html")?.data')
  lines.push("}")
  lines.push("")
  lines.push("export function getAsset(path: string): EmbeddedAsset | undefined {")
  lines.push('  // path should be like "assets/filename.js"')
  lines.push('  const normalized = path.startsWith("/") ? path : `/${path}`')
  lines.push("  return embeddedAssets.get(normalized)")
  lines.push("}")
  lines.push("")
  
  return lines.join("\n")
}

async function main(): Promise<void> {
  console.log("📦 Generating embedded assets module...")
  
  // Check if dist exists
  if (!existsSync(DIST_DIR)) {
    console.log("⚠️  Kanban dist not found, building first...")
    
    // Install and build
    await $`cd ${KANBAN_VUE_DIR} && npm install`.quiet()
    await $`cd ${KANBAN_VUE_DIR} && npm run build`.quiet()
  }
  
  // Collect all files
  console.log("  → Scanning dist directory...")
  const files = collectFiles(DIST_DIR)
  console.log(`  → Found ${files.length} files`)
  
  // Generate the module
  console.log("  → Generating TypeScript module...")
  const moduleContent = generateAssetsModule(files)
  
  // Write the file
  await Bun.write(OUTPUT_FILE, moduleContent)
  
  // Calculate sizes
  const totalSize = files.reduce((sum, f) => sum + f.data.length, 0)
  const sizeKB = (totalSize / 1024).toFixed(1)
  
  console.log(`  ✓ Generated ${OUTPUT_FILE}`)
  console.log(`  📊 Total embedded size: ${sizeKB} KB (${files.length} files)`)
}

// Run if called directly
if (import.meta.main) {
  void main().catch((err) => {
    console.error("❌ Failed:", err)
    process.exit(1)
  })
}

export { collectFiles, generateAssetsModule, getContentType }
