#!/usr/bin/env bun
/**
 * Generate embedded assets module for compiled binary
 * 
 * This script reads all files from kanban-vue/dist, extensions/, and skills/
 * and generates a TypeScript module that exports them as data URIs or strings 
 * that can be served directly or extracted to the filesystem.
 */

import { $ } from "bun"
import { existsSync, readdirSync, statSync, readFileSync } from "fs"
import { resolve, join, relative } from "path"

const PROJECT_ROOT = resolve(import.meta.dir, "..")
const KANBAN_VUE_DIR = join(PROJECT_ROOT, "src", "kanban-vue")
const DIST_DIR = join(KANBAN_VUE_DIR, "dist")
const ASSETS_DIR = join(DIST_DIR, "assets")
const OUTPUT_FILE = join(PROJECT_ROOT, "src", "server", "generated-assets.ts")

// Resource directories for embedding
const EXTENSIONS_DIR = join(PROJECT_ROOT, "extensions")
const SKILLS_DIR = join(PROJECT_ROOT, "skills")
const CONFIG_DIR = join(PROJECT_ROOT, "src", "config")
const DOCKER_DIR = join(PROJECT_ROOT, "docker")

interface AssetFile {
  path: string
  relativePath: string
  contentType: string
  isText: boolean
  data: string
  // Resource type for categorization
  resourceType: "kanban" | "extension" | "skill" | "config" | "docker"
}

function getContentType(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase()
  const types: Record<string, string> = {
    html: "text/html",
    js: "application/javascript",
    ts: "application/typescript",
    css: "text/css",
    svg: "image/svg+xml",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    woff2: "font/woff2",
    woff: "font/woff",
    ttf: "font/ttf",
    json: "application/json",
    ico: "image/x-icon",
    md: "text/markdown",
  }
  return types[ext || ""] || "application/octet-stream"
}

function shouldInlineAsText(contentType: string): boolean {
  return contentType.startsWith("text/") || 
         contentType === "application/javascript" ||
         contentType === "application/typescript" ||
         contentType === "application/json" ||
         contentType === "text/markdown"
}

function collectFiles(dir: string, basePath: string = "", resourceType: AssetFile["resourceType"]): AssetFile[] {
  const files: AssetFile[] = []
  
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry)
    const relativePath = basePath ? `${basePath}/${entry}` : entry
    const stat = statSync(fullPath)
    
    if (stat.isDirectory()) {
      files.push(...collectFiles(fullPath, relativePath, resourceType))
    } else {
      const contentType = getContentType(entry)
      const isText = shouldInlineAsText(contentType)
      
      if (isText) {
        // Read as text for text files
        const content = readFileSync(fullPath, "utf-8")
        files.push({
          path: fullPath,
          relativePath,
          contentType,
          isText: true,
          data: content,
          resourceType,
        })
      } else {
        // Read as base64 for binary files
        const buffer = readFileSync(fullPath)
        const base64 = buffer.toString("base64")
        files.push({
          path: fullPath,
          relativePath,
          contentType,
          isText: false,
          data: base64,
          resourceType,
        })
      }
    }
  }
  
  return files
}

function generateAssetsModule(allFiles: AssetFile[]): string {
  const lines: string[] = []
  
  lines.push("// Generated by scripts/generate-embedded-assets.ts")
  lines.push("// DO NOT EDIT MANUALLY - This file is auto-generated during build")
  lines.push("")
  lines.push("export interface EmbeddedAsset {")
  lines.push("  contentType: string")
  lines.push("  isText: boolean")
  lines.push("  data: string")
  lines.push("  resourceType: 'kanban' | 'extension' | 'skill' | 'config' | 'docker'")
  lines.push("}")
  lines.push("")
  lines.push("export const embeddedAssets: Map<string, EmbeddedAsset> = new Map([")
  
  for (const file of allFiles) {
    let key: string
    
    if (file.resourceType === "kanban") {
      // Kanban files use their normal paths
      key = file.relativePath.startsWith("assets/") 
        ? `/${file.relativePath}`
        : `/${file.relativePath}`
    } else if (file.resourceType === "extension") {
      // Extensions go under /__embedded__/extensions/
      key = `/__embedded__/extensions/${file.relativePath}`
    } else if (file.resourceType === "skill") {
      // Skills go under /__embedded__/skills/
      key = `/__embedded__/skills/${file.relativePath}`
    } else if (file.resourceType === "config") {
      // Config files go under /__embedded__/config/
      key = `/__embedded__/config/${file.relativePath}`
    } else if (file.resourceType === "docker") {
      // Docker files go under /__embedded__/docker/
      key = `/__embedded__/docker/${file.relativePath}`
    } else {
      key = `/${file.relativePath}`
    }
    
    if (file.isText) {
      // For text files, escape backticks and ${ to prevent template literal issues
      const escaped = file.data
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$/g, "\\$")
        .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      
      lines.push(`  ["${key}", { contentType: "${file.contentType}", isText: true, resourceType: "${file.resourceType}", data: \`${escaped}\` }],`)
    } else {
      // For binary files, store base64
      lines.push(`  ["${key}", { contentType: "${file.contentType}", isText: false, resourceType: "${file.resourceType}", data: "${file.data}" }],`)
    }
  }
  
  lines.push("])")
  lines.push("")
  lines.push("// Convenience accessors")
  lines.push("export function getEmbeddedAsset(path: string): EmbeddedAsset | undefined {")
  lines.push("  // Normalize path - remove leading /kanban-vue/dist if present")
  lines.push('  const normalized = path.replace(/^\\/kanban-vue\\/dist/, "")')
  lines.push("  return embeddedAssets.get(normalized)")
  lines.push("}")
  lines.push("")
  lines.push("export function getIndexHtml(): string | undefined {")
  lines.push('  return embeddedAssets.get("/index.html")?.data')
  lines.push("}")
  lines.push("")
  lines.push("export function getAsset(path: string): EmbeddedAsset | undefined {")
  lines.push('  // path should be like "assets/filename.js"')
  lines.push('  const normalized = path.startsWith("/") ? path : `/${path}`')
  lines.push("  return embeddedAssets.get(normalized)")
  lines.push("}")
  lines.push("")
  lines.push("// Resource accessors for extraction")
  lines.push("export function getAllExtensionAssets(): Array<{ path: string; asset: EmbeddedAsset }> {")
  lines.push("  const result: Array<{ path: string; asset: EmbeddedAsset }> = []")
  lines.push('  const prefix = "/__embedded__/extensions/"')
  lines.push("  for (const [key, asset] of embeddedAssets.entries()) {")
  lines.push("    if (key.startsWith(prefix) && asset.resourceType === 'extension') {")
  lines.push("      const relativePath = key.slice(prefix.length)")
  lines.push("      result.push({ path: relativePath, asset })")
  lines.push("    }")
  lines.push("  }")
  lines.push("  return result")
  lines.push("}")
  lines.push("")
  lines.push("export function getAllSkillAssets(): Array<{ path: string; asset: EmbeddedAsset }> {")
  lines.push("  const result: Array<{ path: string; asset: EmbeddedAsset }> = []")
  lines.push('  const prefix = "/__embedded__/skills/"')
  lines.push("  for (const [key, asset] of embeddedAssets.entries()) {")
  lines.push("    if (key.startsWith(prefix) && asset.resourceType === 'skill') {")
  lines.push("      const relativePath = key.slice(prefix.length)")
  lines.push("      result.push({ path: relativePath, asset })")
  lines.push("    }")
  lines.push("  }")
  lines.push("  return result")
  lines.push("}")
  lines.push("")
  lines.push("// Config accessors for extraction")
  lines.push("export function getAllConfigAssets(): Array<{ path: string; asset: EmbeddedAsset }> {")
  lines.push("  const result: Array<{ path: string; asset: EmbeddedAsset }> = []")
  lines.push('  const prefix = "/__embedded__/config/"')
  lines.push("  for (const [key, asset] of embeddedAssets.entries()) {")
  lines.push("    if (key.startsWith(prefix) && asset.resourceType === 'config') {")
  lines.push("      const relativePath = key.slice(prefix.length)")
  lines.push("      result.push({ path: relativePath, asset })")
  lines.push("    }")
  lines.push("  }")
  lines.push("  return result")
  lines.push("}")
  lines.push("")
  lines.push("// Docker accessors for extraction")
  lines.push("export function getAllDockerAssets(): Array<{ path: string; asset: EmbeddedAsset }> {")
  lines.push("  const result: Array<{ path: string; asset: EmbeddedAsset }> = []")
  lines.push('  const prefix = "/__embedded__/docker/"')
  lines.push("  for (const [key, asset] of embeddedAssets.entries()) {")
  lines.push("    if (key.startsWith(prefix) && asset.resourceType === 'docker') {")
  lines.push("      const relativePath = key.slice(prefix.length)")
  lines.push("      result.push({ path: relativePath, asset })")
  lines.push("    }")
  lines.push("  }")
  lines.push("  return result")
  lines.push("}")
  lines.push("")
  
  return lines.join("\n")
}

async function main(): Promise<void> {
  console.log("📦 Generating embedded assets module...")
  
  // Check if dist exists
  if (!existsSync(DIST_DIR)) {
    console.log("⚠️  Kanban dist not found, building first...")
    
    // Install and build
    await $`cd ${KANBAN_VUE_DIR} && npm install`.quiet()
    await $`cd ${KANBAN_VUE_DIR} && npm run build`.quiet()
  }
  
  const allFiles: AssetFile[] = []
  
  // Collect kanban files
  console.log("  → Scanning dist directory...")
  const kanbanFiles = collectFiles(DIST_DIR, "", "kanban")
  allFiles.push(...kanbanFiles)
  console.log(`  → Found ${kanbanFiles.length} kanban files`)
  
  // Collect extension files
  if (existsSync(EXTENSIONS_DIR)) {
    console.log("  → Scanning extensions directory...")
    const extensionFiles = collectFiles(EXTENSIONS_DIR, "", "extension")
    allFiles.push(...extensionFiles)
    console.log(`  → Found ${extensionFiles.length} extension files`)
  } else {
    console.log("  → No extensions directory found, skipping...")
  }
  
  // Collect skill files
  if (existsSync(SKILLS_DIR)) {
    console.log("  → Scanning skills directory...")
    const skillFiles = collectFiles(SKILLS_DIR, "", "skill")
    allFiles.push(...skillFiles)
    console.log(`  → Found ${skillFiles.length} skill files`)
  } else {
    console.log("  → No skills directory found, skipping...")
  }

  // Collect config files (only JSON files, not TypeScript sources)
  if (existsSync(CONFIG_DIR)) {
    console.log("  → Scanning config directory...")
    const configFiles = collectFiles(CONFIG_DIR, "", "config").filter(f => f.relativePath.endsWith('.json'))
    allFiles.push(...configFiles)
    console.log(`  → Found ${configFiles.length} config files`)
  } else {
    console.log("  → No config directory found, skipping...")
  }

  // Collect docker files
  if (existsSync(DOCKER_DIR)) {
    console.log("  → Scanning docker directory...")
    const dockerFiles = collectFiles(DOCKER_DIR, "", "docker")
    allFiles.push(...dockerFiles)
    console.log(`  → Found ${dockerFiles.length} docker files`)
  } else {
    console.log("  → No docker directory found, skipping...")
  }
  
  console.log(`  → Total: ${allFiles.length} files`)
  
  // Generate the module
  console.log("  → Generating TypeScript module...")
  const moduleContent = generateAssetsModule(allFiles)
  
  // Write the file
  await Bun.write(OUTPUT_FILE, moduleContent)
  
  // Calculate sizes
  const totalSize = allFiles.reduce((sum, f) => sum + f.data.length, 0)
  const sizeKB = (totalSize / 1024).toFixed(1)
  
  console.log(`  ✓ Generated ${OUTPUT_FILE}`)
  console.log(`  📊 Total embedded size: ${sizeKB} KB (${allFiles.length} files)`)
}

// Run if called directly
if (import.meta.main) {
  void main().catch((err) => {
    console.error("❌ Failed:", err)
    process.exit(1)
  })
}

export { collectFiles, generateAssetsModule, getContentType }
